### ISSUE TITLE
Connection reset error

### ISSUE THREAD

**Issue by Endeavour79** [tonikelope/megabasterd#27]
FYI, lot's of Error count in the downloads and getting this all the time in the console.
Using standard settings in your app (latest release).

Sep. 17, 2018 2:43:07 PM com.tonikelope.megabasterd.ChunkDownloader run
SEVERE: null
java.net.SocketException: Connection reset
        at java.base/java.net.SocketInputStream.read(Unknown Source)
        at java.base/java.net.SocketInputStream.read(Unknown Source)
        at java.base/java.io.BufferedInputStream.fill(Unknown Source)
        at java.base/java.io.BufferedInputStream.read1(Unknown Source)
        at java.base/java.io.BufferedInputStream.read(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
        at com.tonikelope.megabasterd.ChunkDownloader.run(ChunkDownloader.java:216)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by tonikelope** [comment]
Please, put some example link.
