### ISSUE TITLE
Can't open MegaCrypter links with HTTPS

### ISSUE THREAD

**Issue by BakasuraRCE** [tonikelope/megabasterd#37]
Hi,

Version: 5.70

I'm running a local version of MegaCrypter over HTTPS in a self-signed certificate, when MegaBasterd tries to open it it returns this exception:

```
Nov 09, 2018 9:20:10 PM com.tonikelope.megabasterd.ClipboardSpy _setEnabled
INFO: AWT-EventQueue-0 Monitoring clipboard ON...
Nov 09, 2018 9:20:25 PM com.tonikelope.megabasterd.ClipboardSpy _setEnabled
INFO: AWT-EventQueue-0 Monitoring clipboard OFF...
Nov 09, 2018 9:20:25 PM com.tonikelope.megabasterd.MegaCrypterAPI _rawRequest
SEVERE: null
javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative names present
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
	at com.tonikelope.megabasterd.MegaCrypterAPI._rawRequest(MegaCrypterAPI.java:66)
	at com.tonikelope.megabasterd.MegaCrypterAPI.getMegaFileMetadata(MegaCrypterAPI.java:151)
	at com.tonikelope.megabasterd.Download.getMegaFileMetadata(Download.java:1428)
	at com.tonikelope.megabasterd.Download.provisionIt(Download.java:919)
	at com.tonikelope.megabasterd.DownloadManager._provision(DownloadManager.java:105)
	at com.tonikelope.megabasterd.DownloadManager.provision(DownloadManager.java:74)
	at com.tonikelope.megabasterd.TransferenceManager$6.run(TransferenceManager.java:455)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.cert.CertificateException: No subject alternative names present
	at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:145)
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:94)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:200)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
	... 22 more
```

Could you disable HTTPS certificate verification?

**Comment by tonikelope** [comment]
Try using running MegaBasterd from command line with:

`java -Dcom.sun.net.ssl.checkRevocation=false -jar MegaBasterd_xxx.jar`

Regards.
