### ISSUE TITLE
[REQ] Ability to add bulk mega accounts instead of one at a time

### ISSUE THREAD

**Issue by PatrickJ21** [tonikelope/megabasterd#439]
Hi,

Please add a feature so you can paste accounts email:password format.
i want to add 20+ accounts at once and do not want to add them one by one.

It'd be really appreciated and I'm sure many others want this added.

**Comment by ashes-xda** [comment]
Try this
-add all your accounts to contacts and after that give "all access" to all accounts or choose one primary account from where you want to manage others (I prefer to give all account full access of each other)
-now you can manage (move, delete data) of all your accounts added as contacts from one account from "incoming share"

**Comment by tonikelope** [comment]
EMAIL#PASSWORD

**Comment by PatrickJ21** [comment]
Boss, thank you for adding the option, however since i updated i am having this bug when trying to 'upload'
https://prnt.sc/0zSRgC3IG5_k

**Comment by tonikelope** [comment]
Please, enable debug log in advanced settings and paste here. 

I recommend you anyway to export your settings in advanced settings and try with a clean version to load your old settings.

**Comment by PatrickJ21** [comment]
I've exported and imported like you suggested now, but the same thing happened - here's the log :

Windows Server 2019OpenJDK 64-Bit Server VM 14.0.1 L:\MegaBasterdWINDOWS_7.57\MegaBasterdWINDOWS\jre
Exception in thread "pool-1-thread-8" java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
	at com.tonikelope.megabasterd.MiscTools.lambda$static$0(MiscTools.java:96)
	at java.base/java.util.TimSort.countRunAndMakeAscending(Unknown Source)
	at java.base/java.util.TimSort.sort(Unknown Source)
	at java.base/java.util.Arrays.sort(Unknown Source)
	at java.base/java.util.ArrayList.sort(Unknown Source)
	at java.base/java.util.Collections.sort(Unknown Source)
	at com.tonikelope.megabasterd.MiscTools._sortTreeNode(MiscTools.java:571)
	at com.tonikelope.megabasterd.MiscTools.sortTree(MiscTools.java:551)
	at com.tonikelope.megabasterd.FileGrabberDialog._file_drop_notify(FileGrabberDialog.java:977)
	at com.tonikelope.megabasterd.FileGrabberDialog.lambda$new$5(FileGrabberDialog.java:175)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by tonikelope** [comment]
It's a regression of 7.56 and 7.57 Working on it Thanks

**Comment by tonikelope** [comment]
Fixed (I hope)

Regards.

**Comment by ashes-xda** [comment]
> Fixed (I hope)
> 
> Regards.

Wow fixing issues on New Year's too amazing work.....
Look out for this too #437 thanks

**Comment by tonikelope** [comment]
> > Fixed (I hope)
> > Regards.
> 
> Wow fixing issues on New Year's too amazing work..... Look out for this too #437 thanks

Hahaha, here is still a few hours away and it was a serious bug. While dinner is being made... The thumbnails functionality is not a trivial thing. I will look into it for the next update.

Happy 2023

**Comment by PatrickJ21** [comment]
Thank you [tonikelope](https://github.com/tonikelope) for fixing this fast. I can confirm it works perfectly now.

Happy new year!
