### ISSUE TITLE
Download not Starting/Timing out

### ISSUE THREAD

**Issue by cam-au** [tonikelope/megabasterd#499]
Trying to add individual file links from a VERY large MEGA (approx 20tb) however they are not loading.

Add multiple or individual links as usual. (I have tried many different files from various sub-folders, all with same results).
Megabasterd stops and thinks for a while & the 'New Download' button in file menu is grayed out.
After a while, no download is added and the 'New Download' button returns to normal.

I tried then adding the root folder, and got the usual "Folder link detected" screen with the progress bar 'thinking'. After 10+ mins, it was still thinking.
Not a programmer and don't know how the program works, but my only suspicion is that because of the way Megabasterd finds the download links, it's timing out because of the stupidly large MEGA.

Have tried on multiple different program versions over the past few days (keeping up with the updates) with no success.

Unsure if this is a glitch or known limitation (looking for confirmation. Understand if this may not be an easy fix)
The only workaround I can think of (other than normal downloads) would be to save them to another account/Cloud Drive and then download.

**Comment by tonikelope** [comment]
Hi. It could be an error with some file inside the folder, although it
seems to be due to the huge size of the folder (which will also have many
subfolders). Please send me the link to the folder so I can test it and
maybe optimize the reading process of the folder. You can do it by email if
you don't want to make it public.

Best regards.

**Comment by tonikelope** [comment]
Hi. I have already tested [cam-au](https://github.com/cam-au) 20TB link privately and it loads without errors (it takes 1:30 but it loads perfectly). I don't know what could be happening to you. It could be some connection problem but I can't do much more. Try adding a smaller subfolder to download instead of the whole folder or import the subfolder to another MEGA account. Sorry I can't be of more help :( :(

**Comment by cam-au** [comment]
For the help of others (Toni confirmed as above that the link did work, so was an issue on my PC/Connection):
Enabled Debugging within the settings Window and then searched and found the '.MEGABASTERD_DEBUG.log' file (should be in default user directory or '\MegaBasterdWINDOWS\jar' folder.

Found I was repeatedly getting the below error (retrying every 10 seconds):
```
WARNING: pool-1-thread-13 MegaAPI ERROR -3 Waiting for retry...
Jan 11, 2023 11:17:34 AM com.tonikelope.megabasterd.MegaAPI _rawRequest
WARNING: pool-1-thread-13 MegaAPI ERROR -3 Waiting for retry...
Jan 11, 2023 11:17:43 AM com.tonikelope.megabasterd.MegaAPI _rawRequest
WARNING: pool-1-thread-13 MegaAPI ERROR -3 Waiting for retry...
```
(Ran 28 times, but unsure if that is a special number or just how long it took)

Before it would then time out completely:
```
Jan 11, 2023 11:19:54 AM com.tonikelope.megabasterd.MegaAPI _rawRequest
SEVERE: Unexpected end of file from server
Jan 11, 2023 11:19:54 AM com.tonikelope.megabasterd.MegaAPI getNlinks
SEVERE: null
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `[Ljava.util.HashMap;` from Integer value (token `JsonToken.VALUE_NUMBER_INT`)
 at [Source: (String)"-3"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1322)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.handleNonArray(ObjectArrayDeserializer.java:343)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:194)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:24)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516)
	at com.tonikelope.megabasterd.MegaAPI.getNLinksFromFolder(MegaAPI.java:1228)
	at com.tonikelope.megabasterd.MegaAPI.getNlinks(MegaAPI.java:1203)
	at com.tonikelope.megabasterd.MainPanelView.lambda$new_download_menuActionPerformed$17(MainPanelView.java:1054)
	at com.tonikelope.megabasterd.TransferenceManager.lambda$run$30(TransferenceManager.java:765)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

the MEGA documentation (https://mega.io/doc) mentions that error -3 is:
> API_EAGAIN (-3) (always at the request level): A temporary congestion or server malfunction prevented your request from being processed. No data was altered. Retry. Retries must be spaced with exponential backoff.

Annoyingly, I was successfully able to connect and download 1 file (I was testing to try to get the log) but haven't again been able to. I normally run with a VPN on (and the success was while it was off), but no matter on or off or any change in VPN or even Anti Virus/Firewall settings seem to make a difference.
