### ISSUE TITLE
SQL error or missing database

### ISSUE THREAD

**Issue by drtaru** [tonikelope/megabasterd#627]
When upgrading to 8.17/8 from 8.16 I get the following error. looks like the settings DB isn't being parsed correctly
`Dec 08, 2023 6:02:11 PM com.tonikelope.megabasterd.DBTools selectSettingValue`
`SEVERE: [SQLITE_ERROR] SQL error or missing database (no such table: settings)`

**Comment by tonikelope** [comment]
Related with https://github.com/tonikelope/megabasterd/issues/623

Fix in v8.20

**Comment by drtaru** [comment]
The `Megabasterd.db` file still isnt getting migrated from .Megabasterd8.16 to .Megabasterd8.20 correctly and is also not getting created on a brand new install.

If I manually rename `.Megabasterd8.16/Megabasterd.db` to `.Megabasterd8.20/Megabasterd.db` the app opens and works perfectly (except Dark mode which doesnt change anything on mac).

When copying the new JAR file to the portable dir without moving the DB file manually the following log messages pop up:
```Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.MainPanel loadUserSettings
SEVERE: null
java.sql.SQLException: database connection closed
	at org.sqlite.SQLiteConnection.checkOpen(SQLiteConnection.java:429)
	at org.sqlite.jdbc4.JDBC4Connection.createStatement(JDBC4Connection.java:23)
	at org.sqlite.jdbc3.JDBC3Connection.createStatement(JDBC3Connection.java:169)
	at com.tonikelope.megabasterd.DBTools.selectMegaAccounts(DBTools.java:458)
	at com.tonikelope.megabasterd.MainPanel.loadUserSettings(MainPanel.java:747)
	at com.tonikelope.megabasterd.MainPanel.<init>(MainPanel.java:267)
	at com.tonikelope.megabasterd.MainPanel.main(MainPanel.java:147)

Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.MainPanel loadUserSettings
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.DBTools selectSettingValue
SEVERE: database connection closed
Mac OS XOpenJDK 64-Bit Server VM 11.0.21 /Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jre
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.MiscTools GUIRunAndWait
SEVERE: null
java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at com.tonikelope.megabasterd.MiscTools.GUIRunAndWait(MiscTools.java:647)
	at com.tonikelope.megabasterd.MainPanelView.<init>(MainPanelView.java:456)
	at com.tonikelope.megabasterd.MainPanel.<init>(MainPanel.java:296)
	at com.tonikelope.megabasterd.MainPanel.main(MainPanel.java:147)
Caused by: java.lang.NullPointerException
	at com.tonikelope.megabasterd.DBTools.selectSettingValue(DBTools.java:329)
	at com.tonikelope.megabasterd.MainPanelView.lambda$new$8(MainPanelView.java:539)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.MainPanel _check_old_version
SEVERE: No such file or directory
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.MainPanel lambda$resumeDownloads$14
SEVERE: null
java.lang.NullPointerException
	at com.tonikelope.megabasterd.DBTools.selectDownloadsQueue(DBTools.java:78)
	at com.tonikelope.megabasterd.MainPanel.lambda$resumeDownloads$14(MainPanel.java:1246)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.SqliteSingleton getConn
SEVERE: path to '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20/megabasterd.db': '/Users/drtaru/Downloads/MegaBasterdMACOS_SILICON/jar/.megabasterd8.20' does not exist
Dec 09, 2023 8:26:14 AM com.tonikelope.megabasterd.MainPanel lambda$resumeUploads$20
SEVERE: null
java.lang.NullPointerException
	at com.tonikelope.megabasterd.DBTools.selectUploadsQueue(DBTools.java:123)
	at com.tonikelope.megabasterd.MainPanel.lambda$resumeUploads$20(MainPanel.java:1453)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by tonikelope** [comment]
Yes, 8.17-8.19 db files are corrupted. Its required copying 8.16 to 8.20 folder

**Comment by tonikelope** [comment]
Likely fixed in audit-fixes branch (commits 6bb67ae + c24a6ef). Settings + DB lifecycle improvements.
